language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
before_install:
  - npm i
before_script:
  - npm prune
script:
  - npm run test:no-watch
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release" && npm publish
branches:
  only:
    - master
